apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-platform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Prudhvi25-ef/platform.git
    targetRevision: main
    path: charts/app

  destination:
    server: https://kubernetes.default.svc
    namespace: platform-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
