name: Platform CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io/prudhvi25-ef
  IMAGE_NAME: backend
  ENV_FILE: environments/dev/values.yaml

jobs:
  platform-pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Version
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$VERSION apps/backend

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u prudhvi25-ef --password-stdin

      - name: Push Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$VERSION

      - name: Update Helm values.yaml
        run: |
          sed -i "s/tag:.*/tag: $VERSION/" $ENV_FILE

      # ✅ FIXED COMMIT STEP (IMPORTANT)
      - name: Commit Changes
        run: |
          git config user.name "ci-bot"
          git config user.email "ci@platform.com"
          git add environments/dev/values.yaml
          git commit -m "update image tag to $VERSION" || echo "No changes"
          git push
